name: Build
on:
  pull_request:
  push:
    branches: [main, actions]
    tags: ['v*']
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-15, ubuntu-22.04]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Linux Build Dependencies
        if: runner.os == 'linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y \
            mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libegl1-mesa-dev libvulkan-dev \
            libxext-dev libxrandr-dev libxfixes-dev libxcursor-dev libxss-dev libxi-dev libxkbcommon-dev \
            libwayland-dev libdecor-0-dev libdbus-1-dev libibus-1.0-dev fcitx-libs-dev \
            libudev-dev libunwind-dev libdirectfb-dev libasound2-dev libpulse-dev \
            libpipewire-0.3-dev libgbm-dev ninja-build

      - name: Setup macOS Build Dependencies
        if: ${{ runner.os == 'macOS' }}
        run: brew install ninja

      - name: Build with autobuild
        uses: secondlife/action-autobuild@v5
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
        with:
          public: true
